version: '3.8'

services:
  web:
    image: node:14
    restart: on-failure
    user: node
    working_dir: /app
    environment:
      - PORT=3000
      - MONGO_CONNECTION=mongodb://root:root@db:27017/myapp?authSource=admin
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: sh -c "npm i && npm run start"
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: myapp